doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    driver: 'pdo_mysql'
    server_version: 'mariadb-10.3.22'
    charset: utf8
    default_table_options:
      charset: utf8
      collate: utf8_general_ci
    types:
      UserId: SensitiveUser\User\Infrastructure\Domain\Doctrine\Aggregate\DoctrineUserId
  orm:
    auto_generate_proxy_classes: true
    #naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    #auto_mapping: true
    entity_managers:
      default:
        mappings:
          User:
            is_bundle: false
            type: xml
            dir: "%kernel.project_dir%/src/SensitiveUser/User/Infrastructure/Domain/Doctrine/Persistence/Mapping"
            prefix: 'SensitiveUser\User\Domain'