version: '3.8'

volumes:
#  app_memcached: {}
  app_database: {}

networks:
  gestore_utenti_network:
    name: gestore_utenti_network
    driver: bridge

services:

#  web_server:
#    build: nginx
#    depends_on:
#      - php_gestore_utenti
#    volumes:
#      - ./nginx/symfony-5.conf:/etc/nginx/conf.d/default.conf
#      - ../:/var/www/app
#      - ./logs/nginx/:/var/log/nginx
#    networks:
#      - gestore_utenti_network

  php_gestore_utenti:
    build: php
    hostname: gestu
    volumes:
      - ../:/var/www/app:delegated
      - ./data/shell_history:/home/utente/shell_history
    networks:
      - gestore_utenti_network
    environment:
      - HISTFILE=/home/utente/shell_history/.x_history
    secrets:
      - source: id_rsa
        target: /home/utente/.ssh/id_rsa
      - source: id_rsa.pub
        target: /home/utente/.ssh/id_rsa.pub
      - source: known_hosts
        target: /home/utente/.ssh/known_hosts

#  servicedb:
#    image: amazon/dynamodb-local:1.15.0
#    hostname: dynamodb-local
#    networks:
#      - gestore_utenti_network

  nodejs:
    build: nodejs
    working_dir: /var/www/app
    #command: "commitlint -e --from=HEAD"
    volumes:
      - ../:/var/www/app
    networks:
      - gestore_utenti_network

  servicedb:
    image: mariadb:10.3.22
    volumes:
      - app_database:/var/lib/mysql
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gestore_utenti
    #command: mysqld --sql_mode="" #Per mysql, non serve per mariadb
    networks:
      - gestore_utenti_network