version: '3.9'

volumes:
  broadway-sensitive-serializer-demo-database-volume: {}

networks:
  broadway-sensitive-serializer-demo-network:
    name: broadway-sensitive-serializer-demo-network
    driver: bridge

services:

  broadway-sensitive-serializer-demo-php:
    image: broadway-sensitive-serializer-demo-php
    build: php
    hostname: sensitive_serializer_demo
    volumes:
      - ../:/var/www/app:delegated
      - ./data/shell_history:/home/utente/shell_history
    networks:
      - broadway-sensitive-serializer-demo-network
    environment:
      - HISTFILE=/home/utente/shell_history/.x_history
    secrets:
      - source: id_rsa
        target: /home/utente/.ssh/id_rsa
      - source: id_rsa.pub
        target: /home/utente/.ssh/id_rsa.pub
      - source: known_hosts
        target: /home/utente/.ssh/known_hosts

  broadway-sensitive-serializer-demo-nodejs:
    image: broadway-sensitive-serializer-demo-nodejs
    build: nodejs
    working_dir: /var/www/app
    volumes:
      - ../:/var/www/app
    networks:
      - broadway-sensitive-serializer-demo-network

  broadway-sensitive-serializer-demo-db:
    image: mariadb:10.3.22
    volumes:
      - broadway-sensitive-serializer-demo-database-volume:/var/lib/mysql
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=serializer_demo_db
    networks:
      - broadway-sensitive-serializer-demo-network