services:
  _defaults:
    autowire: true
    autoconfigure: true

  SensitiveUser\User\Domain\Aggregate\Users:
    alias: SensitiveUser\User\Infrastructure\Domain\Broadway\Aggregate\BroadwayUsers

  SensitiveUser\User\Domain\ReadModel\ListUser\ListUsers:
    alias: SensitiveUser\User\Infrastructure\Domain\Doctrine\ReadModel\DoctrineListUsers

  DDDStarterPack\Service\Application\TransactionalSession:
    alias: DDDStarterPack\Service\Infrastructure\Doctrine\DoctrineTransactionalSession