services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

#  SensitiveUser\User\Application\Service\:
#    resource: '%kernel.project_dir%/src/SensitiveUser/User/Application/Service/*'
#    #exclude:  '%kernel.project_dir%/src/SensitiveUser/User/Application/Service/**/{*Request.php,*Exception.php,MakeTheMove.php,ShowPlayStatus.php}'

  SensitiveUser\User\Application\Service\ShowUserList: ~

  SensitiveUser\User\Application\Service\ForgetUser:
    arguments:
      $aggregateKeyManager: "@broadway_sensitive_serializer.aggregate_key_manager"
      
  SensitiveUser\User\Application\Service\UserReplayer:
    arguments:
      $eventStore: "@broadway.event_store.dbal"

  SensitiveUser\User\Application\Service\RegisterUserTransactional:
    arguments:
      $service: '@SensitiveUser\User\Domain\Service\RegisterUser'
