services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SensitiveUser\User\Application\Service\:
    resource: '%kernel.project_dir%/src/SensitiveUser/User/Application/Service/*'
    #exclude:  '%kernel.project_dir%/src/SensitiveUser/User/Application/Service/**/{*Request.php,*Exception.php,MakeTheMove.php,ShowPlayStatus.php}'