name: "Check dependencies"

on:
  pull_request: ~
  workflow_dispatch: ~
  push:
    branches:
      - whole_strategy
      - custom_strategy
      - partial_strategy

jobs:
  check-dependencies:
    name: "Check dependencies"
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check dependency vulnerabilities
        run: ./tools/bin/project/project check-deps-vulnerabilities