name: "Static analysis"

on:
  pull_request: ~
  workflow_dispatch: ~
  push:
    branches:
      - whole_strategy
      - custom_strategy
      - partial_strategy
#  schedule:
#    - cron: '0 */3 * * *'

jobs:
  static-analysis:
    name: "static analysis"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: bcmath, mbstring, intl, sodium, json

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: "running static analysis"
        run: ./tools/bin/project/project psalm

      - name: "calculating type coverage"
        run: ./tools/bin/project/project type-coverage